location: 
 place: New_York_University
 building: Engineering_School_Building_Six
 floor: '4th_floor'
 scale: 0.01209306372

server:
  host: "128.122.136.173"
  port: 30002
  feedback_freq: 0.1
  FEC: false
  INFERENCE: false
  encoding: "h265"
  sink_type: "video"

IO_root: "/mnt/data/UNav-IO"
