# location: 
#  place: New_York_University
#  building: Engineering_School_Building_Six
#  floor: '4_floor'
#  scale: 0.01209306372

location: 
 place: New_York_University
 building: LOH
 floor: 'Langone5_0'
 scale: 0.03136256924

 #location: 
  #place: New_York_City
  #building: LightHouse
  #floor: '6th_floor'
  #scale: 0.01098358101

server:
  host: "128.122.136.173"
  port: 30002
  feedback_freq: 0.1
  FEC: false
  INFERENCE: false
  encoding: "h265"
  sink_type: "video"

IO_root: "/mnt/data/UNav-IO"
