location: 
 place: New_York_University
 building: 6_MetroTech
 floor: Metrotech_6_Floor_4_With_Stairs
 scale: 0.01209306372

server:
  host: "128.122.136.173"
  port: 30002
  feedback_freq: 0.1
  FEC: false
  DEBUG: true
  INFERENCE: false
  encoding: "h265"
  sink_type: "video"

IO_root: "/mnt/data/UNav-IO"