# location: 
#  place: New_York_City
#  building: LightHouse
#  floor: '6th_floor'
#  scale: 0.01098358101

# IO_root: "/mnt/data/UNav-IO"
# testing_image_folder: '/mnt/data/UNav-IO/logs/New_York_City/LightHouse/6th_floor/23301/images'



location: 
 place: New_York_City
 building: LightHouse
 floor: '3'
 scale: 0.02205862195

IO_root: "/mnt/data/UNav-IO"
testing_image_folder: '/mnt/data/UNav-IO/logs/New_York_City/LightHouse/3/14843/images'



# location: 
#  place: New_York_University
#  building: Engineering_School_Building_Six
#  floor: 'fourth_floor'
#  scale: 0.01209306372

# IO_root: "/mnt/data/UNav-IO"
# testing_image_folder: '/home/unav/Desktop/UNav_server/UNav_develop/Mapping/data/src_images/New_York_University/Engineering_School_Building_Six/fourth_floor/equirectangular_images'



# location: 
#   place: New_York_City
#   building: NYISE_VC
#   floor: 1st
#   scale: 0.1513526317

# IO_root: "/home/unav/Desktop/UNav-IO"
# testing_image_folder: 'images/nyise1'



# location: 
#  place: New_York_University
#  building: New_York_University_Hospital
#  floor: 17_floor
#  scale: 0.02157699999

# IO_root: "/mnt/data/UNav-IO"
# testing_image_folder: '/mnt/data/UNav-IO/logs/New_York_University/New_York_University_Hospital/quick_test'


# location: 
#  place: New_York_University
#  building: LOH
#  floor: 'Langone8_0'
#  scale: 0.03136256924

# IO_root: "/mnt/data/UNav-IO"
# testing_image_folder: '/mnt/data/vinay/logs/Langone8_0/test_images'